---
# services:
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     ports:
#       - 9090:9090
#     command: "--config.file=/etc/prometheus/prometheus.yaml"
#     volumes:
#       - ./config/prometheus.yml:/etc/prometheus/prometheus.yaml:ro
#       - /zfs-pool/prometheus-data:/prometheus
#     restart: unless-stopped
#     networks:
#       - monitoring-net


# networks:
#   monitoring-net:
#     driver: bridge
version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - /zfs-pool/prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    command: "--path.rootfs=/host"
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
