---
networks:
#  proxy-traefik:
#    external: true
  monitoring-net:
    external: true
#    external: true
services:
  grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: grafana-prod-1
    ports:
      - 2284:3000
    volumes:
      - /zfs-pool/grafana-data:/var/lib/grafana
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.grafana.entrypoints=web
#      - traefik.http.routers.grafana.rule=Host(`grafana.peter-seubert.de`)
#      - traefik.http.routers.grafana.entrypoints=websecure
#      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
#      - traefik.http.routers.grafana.tls=true
    networks:
#      - proxy-traefik
      - monitoring-net
#    restart: unless-stopped
