---
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring-net
    volumes:
      - /:/host:ro,rslave
networks:
  monitoring-net:
    driver: bridge